--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/llPushkarll/PocketRadio
branches:
- master
projects:
  PocketRadio:
    path: ""
    libs:
    - src: thebigsmilexd/libnbs/libnbs
      version: ^4.1.0
    - src: thebigsmilexd/customui/customui
      version: ^3.0.0
...
